name: QA CI Pipeline (UI + API + Performance)

on:
  push:
    branches: [ "main" ]

jobs:
  qa-pipeline:
    runs-on: ubuntu-latest

    steps:
    # =========================
    # Checkout Repository
    # =========================
    - name: Checkout repository
      uses: actions/checkout@v4

    # =========================
    # UI Automation (Selenium)
    # =========================
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Run UI Automation Tests
      continue-on-error: true
      run: |
        cd "05-UI-Automation/UI Automation Project/HTU-FinalProject-AsmaaKhasawneh"
        mvn clean test

    # =========================
    # API Testing (Postman - Newman)
    # =========================
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman API Tests
      continue-on-error: true
      run: |
        newman run "03-API-Postman/Final Project API TESTING Asmaa Khasawneh.postman_collection.json" \
        -e "03-API-Postman/HTU-FINAL.postman_environment.json" \
        -d "03-API-Postman/APITesting(DATADRIVEN) - Sheet1.csv"

    # =========================
    # Performance Testing (k6)
    # =========================
    - name: Install k6
      run: |
        sudo gpg -k
        sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg \
        --keyserver hkp://keyserver.ubuntu.com:80 \
        --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
        echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install k6

    - name: Run k6 Performance Tests (Smoke + Load)
      continue-on-error: true
      run: |
        k6 run "04-API-Performance-k6/K6Script.js"
